USE  errockalde;


INSERT INTO talde (izena, web, emaila, telefonoa, deskribapena) VALUES
("RO", " www.ro.com", "ro@gmail.com", "654 376 876","Muy lejos, más allá de las montañas de palabras, alejados de los países de las vocales y las consonantes, viven los textos simulados. Viven aislados en casas de letras, en la costa de la semántica, un gran océano de lenguas. Un riachuelo llamado Pons"),
("LOKO FUNJY", " ", "loko-funky@domeinua.com", "654 376 876"),
("KIMERA", " www.kimera.com", "emailanomar@domeinua.com", "654 376 876","Muy lejos, más allá de las montañas de palabras, alejados de los países de las vocales y las consonantes, viven los textos simulados. Viven aislados en casas de letras, en la costa de la semántica, un gran océano de lenguas. Un riachuelo llamado Pons"),
("IXILIK", " ", "emailanomar@domeinua.com", "654 376 876","Muy lejos, más allá de las montañas de palabras, alejados de los países de las vocales y las consonantes, viven los textos simulados. Viven aislados en casas de letras, en la costa de la semántica, un gran océano de lenguas. Un riachuelo llamado Pons"),
("HERSTURA", " ", "emailanomar@domeinua.com", "654 376 876","Muy lejos, más allá de las montañas de palabras, alejados de los países de las vocales y las consonantes, viven los textos simulados. Viven aislados en casas de letras, en la costa de la semántica, un gran océano de lenguas. Un riachuelo llamado Pons"),
("MALENKONIA", " www.malenkonia.com", "emailanomar@domeinua.com", "","Muy lejos, más allá de las montañas de palabras, alejados de los países de las vocales y las consonantes, viven los textos simulados. Viven aislados en casas de letras, en la costa de la semántica, un gran océano de lenguas. Un riachuelo llamado Pons"),
("SHARON STONER", " www.sharon.com", "emailanomar@domeinua.com", "654 376 876","Muy lejos, más allá de las montañas de palabras, alejados de los países de las vocales y las consonantes, viven los textos simulados. Viven aislados en casas de letras, en la costa de la semántica, un gran océano de lenguas. Un riachuelo llamado Pons"),
("HARTZAK", " www.hartzak.com", "emailanomar@domeinua.com", "654 376 876","Muy lejos, más allá de las montañas de palabras, alejados de los países de las vocales y las consonantes, viven los textos simulados. Viven aislados en casas de letras, en la costa de la semántica, un gran océano de lenguas. Un riachuelo llamado Pons"),
("PAPALAGI", " ", "emailanomar@domeinua.com", "654 376 876"),
("drakes", " www.nireweb.com", "emailanomar@domeinua.com", "654 376 876","Muy lejos, más allá de las montañas de palabras, alejados de los países de las vocales y las consonantes, viven los textos simulados. Viven aislados en casas de letras, en la costa de la semántica, un gran océano de lenguas. Un riachuelo llamado Pons"),
("BENEH", " www.nireweb.com", "emailanomar@domeinua.com", "654 376 876"),
("gela berezia", " www.nireweb.com", "emailanomar@domeinua.com", "654 376 876","Muy lejos, más allá de las montañas de palabras, alejados de los países de las vocales y las consonantes, viven los textos simulados. Viven aislados en casas de letras, en la costa de la semántica, un gran océano de lenguas. Un riachuelo llamado Pons"),
("tRIKIMAILU", " www.nireweb.com", "triki@domeinua.com", "654 376 876"),
("bitz", " www.nireweb.com", "emailanomar@domeinua.com", "654 376 876","Muy lejos, más allá de las montañas de palabras, alejados de los países de las vocales y las consonantes, viven los textos simulados. Viven aislados en casas de letras, en la costa de la semántica, un gran océano de lenguas. Un riachuelo llamado Pons"),