#!/bin/bash

if [ "$1" == "debug=1" ] || [ "$1" == "-d" ]; then
    DEBUG=" --debug "
else
    DEBUG=""
fi

clear
phpunit --verbose --colors --test-suffix _test.php $DEBUG .

echo "
****************************************
 TESTING DATAHANDLER/DATAHELPER
****************************************
"

phpunit --verbose --colors --test-suffix .php $DEBUG tests/core/data/
